amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

keycloak:
  realm: codeflix
  host: http://localhost:8443

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:3307

server:
  port: 8080
  undertow:
    threads:
      worke: 10
      io: 2