services:
  mysql:
    container_name: adm_video_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - 3307:3306
    networks:
      - adm_video_network

networks:
  adm_video_network: